# Generated by Django 5.2.6 on 2026-02-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('OTP_VERIFIED', 'OTP Verified'), ('KYC_SUBMITTED', 'KYC Submitted'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved (by SuperAdmin)'), ('LOGIN_ENABLED', 'Login Enabled')], default='REGISTERED', max_length=20),
        ),
    ]
