# Generated by Django 5.2.6 on 2026-02-10 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0002_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='otp_type',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
