# Generated by Django 5.2.6 on 2026-02-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0005_clear_otp_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_otp_verified',
            field=models.BooleanField(default=False, help_text='Tracks if user has completed first login OTP verification'),
        ),
    ]
