# Generated by Django 5.2.6 on 2026-02-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0006_customuser_first_login_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='customer_email',
        ),
    ]
