# Generated by Django 5.2.6 on 2026-02-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0007_remove_kyc_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='drug_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
