# Generated by Django 5.2.6 on 2026-02-17 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0008_kyc_drug_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='customer_mobile',
        ),
        migrations.AddField(
            model_name='kyc',
            name='shop_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='shop_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Phone number must be 10-15 digits')]),
        ),
    ]
