# Generated by Django 5.2.6 on 2026-02-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0009_remove_kyc_customer_mobile_kyc_shop_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='customer_name',
        ),
    ]
