# Generated by Django 5.2.6 on 2026-02-17 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0010_remove_kyc_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='store_photo',
            field=models.FileField(help_text='Front view of store - direct camera picture or document (PDF, JPG, JPEG, PNG)', upload_to='kyc/store_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
