# Generated by Django 5.2.6 on 2026-03-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0023_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude from GPS/map', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude from GPS/map', null=True),
        ),
    ]
