# Generated by Django 5.2.6 on 2026-04-08 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspharmaapp', '0026_alter_salesorder_bill_total_alter_salesorder_br_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(help_text='Device registration token from Firebase', max_length=255, unique=True)),
                ('device_type', models.CharField(blank=True, help_text='e.g., ios, android, web', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the token still active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
